FROM node:16.15-bullseye
RUN curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
RUN curl --proto '=https' --tlsv1.2 -sSf 'https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-cli_20.10.14~3-0~debian-bullseye_amd64.deb' > docker-cli.deb 
RUN corepack enable
RUN yarn set version stable
RUN dpkg -i docker-cli.deb
