name: 'Build and deploy to Heroku'
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Lint and check format']
    branches: ['main']
    types:
      - 'completed'

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    runs-on: 'ubuntu-latest'
    name: 'Build and deploy to Heroku'
    container:
      image: 'klasa/fuel-map-frontend-base'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'
      - name: 'Create Docker image'
        run: 'docker build -t klasa/fuel-map-frontend:latest -f Dockerfile .'
      - name: 'Login to Docker Hub'
        uses: 'docker/login-action@v1'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Push image to Docker Hub'
        run: 'docker push klasa/fuel-map-frontend:latest'
      - name: 'Tag image for Heroku'
        run: 'docker tag klasa/fuel-map-frontend:latest registry.heroku.com/fuel-map-frontend/web'
      - name: 'Login to Heroku container registry'
        run: 'heroku container:login'
      - name: 'Push to Heroku container registry'
        run: 'docker push registry.heroku.com/fuel-map-frontend/web'
      - name: 'Deploy image to Heroku'
        run: 'heroku container:release --app fuel-map-frontend web'
